name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        path: /home/runner/work/LeakIXClient/LeakIXClient/src/github.com/LeakIX/LeakIXClient
    - name: Deps
      run: go get -v ./cmd/leakix
      working-directory: /home/runner/work/LeakIXClient/LeakIXClient/src/github.com/LeakIX/LeakIXClient
      env:
        GOPATH: /home/runner/work/LeakIXClient/LeakIXClient
    - name: Build
      run: go build -v ./cmd/leakix
      working-directory: /home/runner/work/LeakIXClient/LeakIXClient/src/github.com/LeakIX/LeakIXClient
      env:
        GOPATH: /home/runner/work/LeakIXClient/LeakIXClient
